# Generated by Django 5.1.6 on 2026-09-21 16:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('ms_teams', 'Microsoft Teams'), ('upload', 'Uploaded recording'), ('other', 'Other')], default='other', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('recording', 'Recording'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='scheduled', max_length=16)),
                ('language', models.CharField(default='en', max_length=16)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_host', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False, help_text="Member of the owner's organisation rather than a guest.")),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('talk_time_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_participants',
                'ordering': ['-is_host', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_label', models.CharField(blank=True, max_length=64)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.meeting')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='meetings.participant')),
            ],
            options={
                'db_table': 'transcript_segments',
                'ordering': ['meeting_id', 'start_ms', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['owner', '-started_at'], name='meeting_owner_started_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status'], name='meeting_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='meeting_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('platform', 'external_id'), name='meeting_unique_external_id_per_platform'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['meeting', 'is_host'], name='participant_meeting_host_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('meeting', 'email'), name='participant_unique_email_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('joined_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='participant_leaves_after_joining'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['meeting', 'start_ms'], name='segment_meeting_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_ms__gte', models.F('start_ms'))), name='segment_ends_after_it_starts'),
        ),
    ]
