# Hand-written: adds the generated artefacts (MeetingSummary, ActionItem).
# Written by hand rather than autogenerated because models.py and
# 0001_initial have pre-existing drift; this migration touches only the two
# new tables and leaves that drift untouched.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("general", "General summary"),
                            ("action_items", "Action items"),
                            ("sales_call", "Sales call"),
                            ("one_on_one", "One-on-one"),
                            ("standup", "Standup"),
                            ("interview", "Interview"),
                            ("custom", "Custom"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("decisions", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_summaries",
                "verbose_name_plural": "meeting summaries",
                "ordering": ["-generated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to="meetings.participant",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_action_items",
                "ordering": [
                    "completed",
                    models.OrderBy(models.F("due_date"), nulls_last=True),
                    "created_at",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="meetingsummary",
            index=models.Index(
                fields=["meeting", "status"], name="summary_meeting_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsummary",
            index=models.Index(fields=["status"], name="summary_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="meetingsummary",
            constraint=models.UniqueConstraint(
                fields=("meeting", "template"), name="summary_unique_template_per_meeting"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingsummary",
            constraint=models.CheckConstraint(
                condition=models.Q(("status", "ready"), _negated=True)
                | models.Q(("generated_at__isnull", False)),
                name="summary_ready_has_generated_at",
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["meeting", "completed"], name="action_item_meeting_open_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["owner", "completed"], name="action_item_owner_open_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(fields=["due_date"], name="action_item_due_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="actionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed", True), ("completed_at__isnull", False))
                | models.Q(("completed", False), ("completed_at__isnull", True)),
                name="action_item_completed_at_matches_completed",
            ),
        ),
    ]
