# Generated by Django 5.1.6 on 2026-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_calendar_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
